articles_data = [
    {
        'id': 4,
        'day': 28,
        'month': 2,
        'year': 2017,
        'image_name': 'mattcorallo.png',
        'file_name': 'bitcoin-trustlessness',
        'title': "Bitcoin's Diversity of Use-Cases and Security Models",
        'author': 'Matt Corallo',
        'source': 'https://bluematt.bitcoin.ninja/2017/02/28/bitcoin-trustlessness/',
        'source_name': "BlueMatt's Blog",
        'preview': "...we have to agree on one thing: what IS Bitcoin? Or, at least, what are the key features of Bitcoin that we must protect as we endeavour to change the system?"
    },
    {
        'id': 3,
        'day': 30,
        'month': 4,
        'year': 2018,
        'image_name': 'cdecker.png',
        'file_name': 'eltoo-simplified-lightning',
        'title': 'eltoo: A Simplified Update Mechanism for Lightning and Off-Chain Contracts',
        'author': 'Christian Decker, Ph.D.',
        'source': 'https://blockstream.com/2018/04/30/eltoo-next-lightning.html',
        'source_name': 'Blockstream',
        'preview': "...eltoo simply enforces the latest agreed-upon state of the off-chain contract. This has important implications for the applicability and safety of the protocols that are built on top of the update mechanism."
    },
    {
        'id': 2,
        'day': 20,
        'month': 11,
        'year': 2017,
        'image_name': 'jimmysong.jpeg',
        'file_name': 'segwit2x-bugs-explained',
        'title': 'Segwit2x Bugs Explained',
        'author': 'Jimmy Song',
        'source': 'https://bitcointechtalk.com/segwit2x-bugs-explained-8e0c286124bc',
        'source_name': 'Bitcoin Tech Talk',
        'preview': "There was a bug in the Segwit2x software which caused the client to stop at block 494782. Examine the details of what caused the software to stop..."
    },
    {
        'id': 1,
        'day': 15,
        'month': 9,
        'year': 2016,
        'image_name': 'starkness.jpg',
        'file_name': 'what-is-the-lightning-network',
        'title': 'What is the Lightning Network and how can it help Bitcoin scale?',
        'author': 'Elizabeth Stark',
        'source': 'https://coincenter.org/entry/what-is-the-lightning-network',
        'source_name': 'Coin Center',
        'preview': "A plain-language explanation of the Lightning Network, a protocol for scaling and speeding up blockchains..."
    },
    {
        'id': 0,
        'day': 29,
        'month': 7,
        'year': 2015,
        'image_name': 'pwuille.png',
        'file_name': 'why-use-a-full-node-wallet',
        'title': 'Why Use a Full Node Wallet',
        'author': 'Pieter Wuille',
        'source': 'https://www.reddit.com/r/BitcoinBeginners/comments/3eq3y7/full_node_question/ctk4lnd/',
        'source_name': 'Reddit',
        'preview': "One of Bitcoin's strengths - the most important in my opinion even - is the low degree of trust you need in others. If you use a full node for your incoming transactions, you know that there was no cheating anytime in the history of your coins..."
    },
]
